name: buzzoole
description: A technical test for Buzzoole 

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  http: ^0.12.2
  shared_preferences: ^2.0.5
  lottie: ^0.7.0+1
  flutter_swiper: ^1.1.6
  smooth_star_rating: ^1.1.1
  favorite_button: ^0.0.3
  transparent_image: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/

  fonts:
    - family: Black
      fonts:
        - asset: assets/fonts/HelveticaNeueCondensedBlack.ttf

    - family: Thin
      fonts:
        - asset: assets/fonts/HelveticaNeueCondensedThin.ttf

    - family: Bold
      fonts:
        - asset: assets/fonts/HelveticaNeueCondensedBold.ttf